### ISSUE TITLE
Missing Intercom type

### ISSUE THREAD

**Issue by Jeffrey-Suitor** [devonik/nuxt-3-intercom#2]
Hello,

Thanks for making this package.

When I installed with pnpm on my nuxt 3.7.4 app there is not type being created for intercom, the intercom.d.ts file is empty. The package is installed and working otherwise but there is not autocomplete.

**Comment by devonik** [comment]
Hey, thanks for using this and for good feedback 👍 . It's a bit tricky to find the right way to define types in nuxt modules. I will have a look on that.

**Comment by devonik** [comment]
I released 1.1.2. The type for module config, runtimeConfig and the plugin itself. Check it please and feedback is always welcome

**Comment by Jeffrey-Suitor** [comment]
Just updated. The types are coming through now. Thank you
