### ISSUE TITLE
Add `showArticle` method

### ISSUE THREAD

**Issue by meirroth** [devonik/nuxt-3-intercom#3]
Can we add the `showArticle` method to this wrapper? Let me know if I should open a PR.
For now I'm using `$intercom.call('showArticle', id)`
https://github.com/devonik/nuxt-3-intercom/blob/27d663f88aed896c55e3751e2be92d211bcd92ca/src/runtime/Intercom.ts#L27-L40

**Comment by devonik** [comment]
Hey, sorry for the late response. I haven't seen a notification.
You're very welcome to open a PR :)

Otherwise I will consider it when I've time

**Comment by meirroth** [comment]
@devonik Done
